[build]
  command = "apt-get update && apt-get install -y coreutils && bash install_emsdk.sh && npm install && npm run build"
  publish = ".next"  # This is NOT needed for Next.js, but won't break anything

[build.environment]
  NODE_VERSION = "18"  # Ensure compatibility with Next.js
  PYTHON_VERSION = "3.10"
  EMSDK = "/opt/buildhome/.emsdk"
  PATH = "/opt/buildhome/.emsdk:/opt/buildhome/.emsdk/upstream/emscripten:$PATH"
